objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>Alert_Detail__c</fullName>
        <label>Alert Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <label>Alert Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Danger</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                    <isActive>false</isActive>
                    <label>Success</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alerts</relationshipLabel>
        <relationshipName>Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>ALT-{0000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Soft Rejection</fullName>
                </value>
                <value>
                    <fullName>Hard Rejection</fullName>
                </value>
                <value>
                    <fullName>Retrying</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Disputed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Bequest</fullName>
        <active>true</active>
        <businessProcess>Bequest</businessProcess>
        <description>Record used to capture details about a bequest that has been pledged by a donor.</description>
        <label>Gifts In Wills</label>
    </recordTypes>
    <recordTypes>
        <fullName>MajorGift</fullName>
        <active>true</active>
        <businessProcess>Major Gift</businessProcess>
        <description>Record used to capture details about a large donation from a major donor.</description>
        <label>Major Gift</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountBadgesCtrl.cls
public class AccountBadgesCtrl extends BadgesBaseCtrl {

    @AuraEnabled
    public static String getBadges(Id recordId) {
        try {
            return JSON.serialize(new BadgesProcessor(recordId).process());
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage() + ' ' + ex.getStackTraceString());
        }
    }

    public class BadgesProcessor {

        private Id recordId;
        private Account accountVar;
        private BadgesResponse response = new BadgesResponse();

        public BadgesProcessor(Id recordId) {
            this.recordId = recordId;
        }

        public BadgesResponse process() {

            retrieveAccount();
            populateBadges();

            return this.response;
        }

        private void retrieveAccount(){
            this.accountVar = (Account)vertic_Utils.arrays.firstOrException(
                [SELECT Id, npo02__OppAmountThisYear__c, RecordType.DeveloperName FROM Account WHERE Id = :this.recordId],
                'No Account with Id: ' + this.recordId
            );
        }

        private void populateBadges() {

            populateAlertIcons();
            populateCarsIcon();
            populateMajorDonorIcon();
            populateIndividualDonorIcon();
            populateRecurringIcon();
//            populateBequestorIcon();
            populateInKindGiftIcon();
            populateWorkplaceGivingIcon();

        }

        private void populateAlertIcons() {

            List<Alert__c> alerts = [
                SELECT Id, Alert_Type__c, Alert_Detail__c
                FROM Alert__c
                WHERE Organisation__c = :this.recordId
                AND Status__c = 'Active'
            ];

            Map<String, Alert__c> alertsByTypes = new Map<String, Alert__c>();
            for (Alert__c alert : alerts) {
                alertsByTypes.put(
                    alert.Alert_Type__c,
                    alert
                );
            }

            if (alertsByTypes.containsKey('Danger')) {
                this.response.badges.add(new Badge(
                    'custom:custom82',
                    alertsByTypes.get('Danger').Alert_Detail__c
                ));
            }

            if (alertsByTypes.containsKey('Warning')) {
                this.response.badges.add(new Badge(
                    'custom:custom53',
                    alertsByTypes.get('Warning').Alert_Detail__c
                ));
            }

            if (alertsByTypes.containsKey('Info')) {
                this.response.badges.add(new Badge(
                    'custom:custom26',
                    alertsByTypes.get('Info').Alert_Detail__c
                ));
            }
        }

        private void populateCarsIcon() {
            List<Opportunity> opportunities = [
                SELECT Amount
                FROM Opportunity
                WHERE AccountId = :this.recordId
                AND
                RecordType.DeveloperName = 'Car_Donation'
                AND StageName = 'Closed Won'
            ];

            Decimal total = 0;
            for (Opportunity opportunityVar : opportunities) {
                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
            }

            if (!opportunities.isEmpty()) {
                this.response.badges.add(new Badge(
                    'custom:custom31',
                    String.format(
                        'Number of cars donated: {0} Total value: {1}',
                        new List<String>{
                            String.valueOf(opportunities.size()),
                            String.valueOf(total)
                        }
                    )
                ));
            }

        }

        private void populateMajorDonorIcon() {
//            List<Opportunity> opportunities = [
//                SELECT Amount
//                FROM Opportunity
//                WHERE AccountId = :this.recordId
//                AND
//                RecordType.DeveloperName = 'MajorGift'
//                AND StageName = 'Closed Won'
//            ];
//
//            Decimal total = 0;
//            for (Opportunity opportunityVar : opportunities) {
//                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
//            }

            Boolean isHousehold = this.accountVar.RecordTypeId != null && 'HH_Account'.equalsIgnoreCase(this.accountVar.RecordType.DeveloperName);

            if(isHousehold && this.accountVar.npo02__OppAmountThisYear__c != null && this.accountVar.npo02__OppAmountThisYear__c > 500){
                this.response.badges.add(new Badge(
                    'custom:custom17',
                    String.format(
                        'Major Donation. Total value: {0}',
                        new List<String>{
                            String.valueOf(this.accountVar.npo02__OppAmountThisYear__c)
                        }
                    )
                ));
            }

//            if (!opportunities.isEmpty()) {
//                this.response.badges.add(new Badge(
//                    'custom:custom17',
//                    String.format(
//                        'Major Donation Count: {0} Total value: {1}',
//                        new List<String>{
//                            String.valueOf(opportunities.size()),
//                            String.valueOf(total)
//                        }
//                    )
//                ));
//            }
        }

//        private void populateMajorGiftIcon() {
//            List<Opportunity> opportunities = [
//                SELECT Amount
//                FROM Opportunity
//                WHERE AccountId = :this.recordId
//                AND
//                RecordType.DeveloperName = 'MajorGift'
//                AND StageName = 'Closed Won'
//            ];
//
//            Decimal total = 0;
//            for (Opportunity opportunityVar : opportunities) {
//                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
//            }
//
//            if (!opportunities.isEmpty()) {
//                this.response.badges.add(new Badge(
//                    'custom:custom17',
//                    String.format(
//                        'Major Donation Count: {0} Total value: {1}',
//                        new List<String>{
//                            String.valueOf(opportunities.size()),
//                            String.valueOf(total)
//                        }
//                    )
//                ));
//            }
//        }

        private void populateIndividualDonorIcon() {
            List<Opportunity> opportunities = [
                SELECT Amount
                FROM Opportunity
                WHERE AccountId = :this.recordId
                AND
                RecordType.DeveloperName = 'Donation'
                AND StageName = 'Closed Won'
            ];

            Decimal total = 0;
            for (Opportunity opportunityVar : opportunities) {
                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
            }

            if (!opportunities.isEmpty()) {
                this.response.badges.add(new Badge(
                    'standard:opportunity',
                    String.format(
                        'Individual Donation Count: {0} Total value: {1}',
                        new List<String>{
                            String.valueOf(opportunities.size()),
                            String.valueOf(total)
                        }
                    )
                ));
            }
        }

        private void populateRecurringIcon() {
            List<Opportunity> opportunities = [
                SELECT Amount
                FROM Opportunity
                WHERE AccountId = :this.recordId
                AND
                RecordType.DeveloperName = 'Recurring_Donation'
                AND StageName = 'Closed Won'
            ];

            Decimal total = 0;
            for (Opportunity opportunityVar : opportunities) {
                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
            }

            if (!opportunities.isEmpty()) {
                this.response.badges.add(new Badge(
                    'custom:custom41',
                    String.format(
                        'Recurring Donation Count: {0} Total value: {1}',
                        new List<String>{
                            String.valueOf(opportunities.size()),
                            String.valueOf(total)
                        }
                    )
                ));
            }
        }

//        private void populateBequestorIcon() {
//            List<Opportunity> opportunities = [
//                SELECT Amount
//                FROM Opportunity
//                WHERE AccountId = :this.recordId
//                AND StageName = 'Bequestor'
//            ];
//
//            Decimal total = 0;
//            for (Opportunity opportunityVar : opportunities) {
//                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
//            }
//
//            if (!opportunities.isEmpty()) {
//                this.response.badges.add(new Badge(
//                    'custom:custom1',
//                    String.format(
//                        'Bequest Opportunity Amount: {1}',
//                        new List<String>{
//                            String.valueOf(opportunities.size()),
//                            String.valueOf(total)
//                        }
//                    )
//                ));
//            }
//        }

        private void populateInKindGiftIcon() {
            List<Opportunity> opportunities = [
                SELECT Amount
                FROM Opportunity
                WHERE AccountId = :this.recordId
                AND
                RecordType.DeveloperName = 'In_Kind_Gift'
                AND StageName = 'Received'
            ];

            Decimal total = 0;
            for (Opportunity opportunityVar : opportunities) {
                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
            }

            if (!opportunities.isEmpty()) {
                this.response.badges.add(new Badge(
                    'standard:thanks',
                    String.format(
                        'In Kind Opportunity Count: {0} Total value: {1}',
                        new List<String>{
                            String.valueOf(opportunities.size()),
                            String.valueOf(total)
                        }
                    )
                ));
            }
        }

        private void populateWorkplaceGivingIcon() {
            List<Opportunity> opportunities = [
                SELECT Amount
                FROM Opportunity
                WHERE AccountId = :this.recordId
                AND
                RecordType.DeveloperName = 'Workplace_Giving'
                AND StageName = 'Closed Won'
            ];

            Decimal total = 0;
            for (Opportunity opportunityVar : opportunities) {
                total += opportunityVar.Amount == null ? 0 : opportunityVar.Amount;
            }

            if (!opportunities.isEmpty()) {
                this.response.badges.add(new Badge(
                    'standard:person_account',
                    String.format(
                        'Workplace Giving Count: {0} Total value: {1}',
                        new List<String>{
                            String.valueOf(opportunities.size()),
                            String.valueOf(total)
                        }
                    )
                ));
            }
        }
    }

}