objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Status__c</fullName>
        <label>Batch Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches (custom)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CentrePayProcessPaymentsBatchTest.cls
@IsTest
private class CentrePayProcessPaymentsBatchTest {
    @IsTest
    static void testBehavior() {
        Batch__c batch = new Batch__c(
            Batch_Status__c = 'In Progress'
        );
        insert batch;

        List<Map<String, Object>> paymentRows = new List<Map<String, Object>>{
            new Map<String, Object>{

            }
        };

        Database.executeBatch(new CentrePayProcessPaymentsBatch(paymentRows, batch.Id));
    }
}