objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Clever_Contacts_Type__c</fullName>
        <label>Clever Contacts Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adoption Conversion</fullName>
                </value>
                <value>
                    <fullName>New Donor Conversion</fullName>
                </value>
                <value>
                    <fullName>Raffle Conversion</fullName>
                </value>
                <value>
                    <fullName>Upgrades</fullName>
                </value>
                <value>
                    <fullName>Re-Activation</fullName>
                </value>
                <value>
                    <fullName>Cat Behaviour Guide</fullName>
                </value>
                <value>
                    <fullName>Happy Dog Guide</fullName>
                </value>
                <value>
                    <fullName>MPW Conversion</fullName>
                </value>
                <value>
                    <fullName>CCD Conversion</fullName>
                </value>
                <value>
                    <fullName>GTGTH Conversion</fullName>
                </value>
                <value>
                    <fullName>Adopt Lead Gen</fullName>
                </value>
                <value>
                    <fullName>AEF</fullName>
                </value>
                <value>
                    <fullName>Competible</fullName>
                </value>
                <value>
                    <fullName>MPW Welcome Calls</fullName>
                </value>
                <value>
                    <fullName>MPW Re-Activation Calls</fullName>
                </value>
                <value>
                    <fullName>GiW Conversion Campaign</fullName>
                </value>
                <value>
                    <fullName>GiW Thank you/Check In Calls</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Clever_Contacts_Sync_Details__c</fullName>
        <label>Clever Contacts Sync Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Clever_Contacts_Sync_Status__c</fullName>
        <label>Clever Contacts Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

classes/CleverContactsSyncMemberBatch.cls
public class CleverContactsSyncMemberBatch implements Database.Batchable<SObject>, Database.AllowsCallouts{

    private String campaignId;
    private String queryString;

    public CleverContactsSyncMemberBatch(String campaignId){
        this.campaignId = campaignId;

        Campaign campaign = (Campaign) vertic_Utils.arrays.firstOrNull([SELECT Id, Clever_Contacts_Type__c FROM Campaign WHERE Id = :campaignId]);

        Map<String, Object> mapping = CleverContactsSyncMemberProc.retrieveMapping(campaign.Clever_Contacts_Type__c);
        if(mapping == null) { throw new vertic_Structs.MissingDataException('Mapping is missing for Campaign!'); }
        SObjectType sObjectType = Schema.getGlobalDescribe().get(mapping.get('object').toString());

        this.queryString = 'SELECT Id, ContactId, Clever_Contacts_Sync_Status__c, Clever_Contacts_Sync_Details__c FROM CampaignMember WHERE CampaignId = \'' + this.campaignId + '\'';
        if(sObjectType == Contact.SObjectType){
            this.queryString += ' AND ContactId != NULL';
        } else if(sObjectType == Lead.SObjectType) {
            this.queryString += ' AND LeadId != NULL';
        }
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(this.queryString);
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {
        CampaignMember member = (CampaignMember) scope[0];
//        try {
            new CleverContactsSyncMemberProc().process(new Map<String, Object>{
                'recordId' => member.Id
            });
//        } catch (Exception e){
//            member.Clever_Contacts_Sync_Status__c = 'Failed';
//            member.Clever_Contacts_Sync_Details__c = e.getMessage();
//            update member;
//        }
    }

    public void finish(Database.BatchableContext context) {
        System.debug('CleverContactsSyncMemberBatch finished!');
    }
}