objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Direct_Mail_Receipt_Template__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Direct Mail Receipt Templates</relationshipLabel>
        <relationshipName>Direct_Mail_Receipt_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Envelope_Type__c</fullName>
        <label>Envelope Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C5</fullName>
                </value>
                <value>
                    <fullName>DLX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Header_Image__c</fullName>
        <label>Header Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Maximum_Donation__c</fullName>
        <label>Maximum Donation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Donation__c</fullName>
        <label>Minimum Donation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Receipt_Body_Text__c</fullName>
        <label>Receipt Body Text</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Direct Mail Receipt Template</label>
    <nameField>
        <label>Direct Mail Receipt Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direct Mail Receipt Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DirectMailReceiptMetaProcTest.cls
@IsTest
public class DirectMailReceiptMetaProcTest {
    @IsTest static void test(){
        Account account = new Account(
            Name = 'testName'
        );
        insert account;

        Contact contact = new Contact(
            LastName = 'test',
            Email = 'test@test.test',
            AccountId = account.Id
        );
        insert contact;

        Campaign campaign = new Campaign(
            Name = 'test'
        );
        insert campaign;

        Opportunity opp = new Opportunity(
            Name = 'test',
            Amount = 10,
            StageName = 'Closed Won',
            CloseDate = Date.today(),
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Donation').getRecordTypeId(),
            npsp__Primary_Contact__c = contact.Id,
            CampaignId = campaign.Id,
            npsp__Acknowledgment_Status__c = 'To Be Acknowledged'
        );
        insert opp;

        Direct_Mail_Receipt_Template__c template = new Direct_Mail_Receipt_Template__c(
            Envelope_Type__c = 'DLX',
            Header_Image__c = 'https://rspcansw--developer--c.documentforce.com/servlet/servlet.FileDownload?file=0151y000000VIsS',
            Receipt_Body_Text__c = '&lt;c:DirectMailReceiptAddress/&gt; &lt;c:DirectMailReceiptImage/&gt; {!today} Dear {!recipient.FirstName} &lt;c:DirectMailReceiptTable/&gt;',
            Minimum_Donation__c = 0,
            Maximum_Donation__c = 99999999,
            Campaign__c = campaign.Id
        );
        insert template;

        DirectMailReceiptMetaProc metaProc = new DirectMailReceiptMetaProc();

        vertic_Response response = metaProc.process(new Map<String, Object>{
            'ids' => opp.Id,
            'renderAs' => 'html',
            'afterProc' => true
        });

        metaProc.getMergeFieldSets();
        metaProc.getSObjectType();

        System.assert(response.isValid);
    }
}