objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <label>Contact ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MigrateContactIdBatchScript.cls
global without sharing class MigrateContactIdBatchScript implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, Contact_ID__c, External_ID__c FROM Contact');
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        for(Contact contact : scope){
//            contact.Contact_ID__c = contact.External_ID__c;
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('MigrateContactIdBatchScript finished!');
    }
}