objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active_Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Membership</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>Membership</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts (Active membership)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <businessProcess>Membership</businessProcess>
        <description>Record used to capture details about a membership.</description>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MembershipService.cls
public without sharing class MembershipService {

    public static void updateActiveMembership(List<Opportunity> memberships){

        if(memberships == null || memberships.isEmpty()){ return; }

        Set<Id> contactIds = (Set<Id>) vertic_Utils.sObjects.getIdFieldValues(memberships, 'npsp__Primary_Contact__c');
        Map<Id, Contact> contactMap = new Map<Id, Contact>([
            SELECT Id, Active_Membership__c
            FROM Contact
            WHERE Id IN :contactIds
        ]);

        List<Opportunity> lastActiveMemberships = new List<Opportunity>();
        for(Opportunity renewalMembership : memberships){
            Contact contact = contactMap.get(renewalMembership.npsp__Primary_Contact__c);

            if(contact == null) { continue; }

            if(contact.Active_Membership__c != null){
                lastActiveMemberships.add(new Opportunity(
                    Id = contact.Active_Membership__c,
                    StageName = 'Closed Won'
                ));
            }

            contact.Active_Membership__c = renewalMembership.Id;
        }

        update contactMap.values();
        update lastActiveMemberships;
    }

    public static List<Opportunity> filterMemberships(List<Opportunity> opportunities, Map<Id ,Opportunity> oldOpportunityMap){
        List<Opportunity> memberships = new List<Opportunity>();

        String membershipRecordType = vertic_Utils.sObjects.recordTypeIdByAPIName(Opportunity.SObjectType, 'Membership');
        for(Opportunity opportunity : opportunities){
            Opportunity oldOpportunity = oldOpportunityMap.get(opportunity.Id);
            if(opportunity.RecordTypeId == membershipRecordType && opportunity.StageName == 'Enrolled' && oldOpportunity.StageName == 'Pending'){
                memberships.add(opportunity);
            }
        }
        return memberships;
    }
}