objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BPAY_CRN__c</fullName>
        <label>BPAY CRN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BPAY_Contract_Reference__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>BPAY Contract Reference</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EzidebitGenerateCRNBatch.cls
public class EzidebitGenerateCRNBatch implements Database.Batchable<SObject>, Database.AllowsCallouts{

    private String campaignId;

    public EzidebitGenerateCRNBatch(String campaignId){
        this.campaignId = campaignId;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT ContactId' +
                                        ' FROM CampaignMember' +
                                        ' WHERE Contact.BPAY_CRN__c = NULL' +
                                        ' AND Contact.BPAY_Contract_Reference__c != NULL' +
                                        ' AND CampaignId = \'' + this.campaignId + '\'');
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {

        try {
            new ContactGenerateCRNActionSubmitProc().process(new vertic_Request(new Map<String, Object>{
                'recordId' => scope[0].get('ContactId')
            }));
        } catch (Exception e){
            hey.Logger.debug(scope[0].get('ContactId'));
            hey.Logger.debug(e.getMessage());
            hey.Logger.publish();
        }

    }

    public void finish(Database.BatchableContext context) {
        System.debug('EzidebitGenerateCRNBatch finished!');
    }
}