objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <label>Contact ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MigrateContactIdBatchScriptTest.cls
@IsTest
public class MigrateContactIdBatchScriptTest {
    static testMethod void test(){

        Contact contact = new Contact(
            LastName = 'test',
            External_ID__c = 'test'
        );
        insert contact;

        Test.startTest();
        Database.executeBatch(new MigrateContactIdBatchScript(), 200);
        Test.stopTest();

        System.assertEquals('test', [SELECT Id, Contact_ID__c FROM Contact LIMIT 1].Contact_ID__c);
    }
}