objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deceased_Date__c</fullName>
        <label>Deceased Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deceased_Date__c</fullName>
        <formula>npsp__Primary_Contact__r.Deceased_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deceased Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Bequest</fullName>
        <active>true</active>
        <businessProcess>Bequest</businessProcess>
        <description>Record used to capture details about a bequest that has been pledged by a donor.</description>
        <label>Gifts In Wills</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactMakeDeceasedActionCtrlTest.cls
@isTest
private class ContactMakeDeceasedActionCtrlTest {
    static testMethod void contactMakeDeceasedActionCtrlTest() {
        Contact contact = new Contact(
            LastName = 'Test Name',
            Email = 'test.name@email.com'
        );
        insert contact;

        Opportunity opp = new Opportunity(
            Name = 'test',
            StageName = 'Enquiry',
            CloseDate = Date.today(),
            npsp__Primary_Contact__c = contact.Id,
            RecordTypeId = vertic_Utils.sObjects.recordTypeIdByName(Opportunity.SObjectType, 'Bequest'));
        insert opp;

        ContactMakeDeceasedActionCtrl.optOutEmailContact(contact.Id);
        ContactMakeDeceasedActionCtrl.makeDeceasedContact(contact.Id, Date.today(), Date.today());

        try {
            ContactMakeDeceasedActionCtrl.makeDeceasedContact('123121', Date.today(), Date.today());
        } catch(Exception e) {
            System.assert(true);
        }

        System.assertEquals(Date.today(), [SELECT Id, Deceased_Date__c FROM Contact LIMIT 1].Deceased_Date__c);
    }
}