objects/Direct_Debit_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>EziDebit_Customer_ID__c</fullName>
        <label>EziDebit Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Direct Debit Schedule</label>
    <nameField>
        <displayFormat>DD-{00000}</displayFormat>
        <label>Direct Debit Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EzidebitGetDDPaymentsScheduledProc.cls
public without sharing class EzidebitGetDDPaymentsScheduledProc extends vertic_ScheduledProc implements Database.Batchable<SObject>, Database.AllowsCallouts {

    /**
     * ==============================================================================================================
     *                                              SCHEDULED PROC OVERRIDES
     * ==============================================================================================================
     */

    public override String getScheduledJobName() {
        return 'EziDebit Get Scheduled Payments - Every Day at 8 PM';
    }

    public override String getScheduledCRON() {
        return '0 0 20 1/1 * ? *'; // Every Day at 8 PM
    }

    public override Type getScheduledProcType() {
        return EzidebitGetDDPaymentsScheduledProc.class;
    }

    public override Boolean isQueueable() {
        return true;
    }

    /**
     * ==============================================================================================================
     *                                              BATCHABLE OVERRIDES
     * ==============================================================================================================
     */

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id FROM Direct_Debit_Schedule__c WHERE Status__c = \'Active\' AND EziDebit_Customer_ID__c != null');
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {
        new EzidebitGetDDPaymentsProc().process(new vertic_Request(new Map<String, Object>{
            'recordId' => scope[0].Id
        }));
    }

    public void finish(Database.BatchableContext context) {
        System.debug('EzidebitGetScheduledPaymentsScheduleProc finished!');
    }

    /**
     * ==============================================================================================================
     *                                              PROCESS
     * ==============================================================================================================
     */

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.response.put('apexJobId', Database.executeBatch(this, 1));

        return this.response;
    }

}