objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <label>Expense Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Funding_Allocation__c.object
<CustomObject>
    <label>Funding Allocation</label>
    <nameField>
        <displayFormat>FUN-{00000}</displayFormat>
        <label>Funding Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program_Budget_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Funds_Remaining__c</fullName>
        <formula>Amount__c - Funds_Spent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Funds Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>pmdm__Program__c</referenceTo>
        <relationshipLabel>Program Budget Allocations</relationshipLabel>
        <relationshipName>Program_Budget_Allocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Budget Allocation</label>
    <nameField>
        <displayFormat>PBA-{00000}</displayFormat>
        <label>Program Budget Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Budget Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExpenceDomain.cls
public without sharing class ExpenceDomain extends fflib_SObjectDomain{

    public ExpenceDomain(List<Task> sObjectList) {
        super(sObjectList);
        Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new ExpenceDomain(sObjectList);
        }
    }
    public override void onBeforeInsert() {
        populateExpenseRelationships(this.Records,null);
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
        populateExpenseRelationships(this.Records, existingRecords);
    }

    private void populateExpenseRelationships(List<Expense__c> expenses, Map<Id, SObject> existingExpenses){

        Set<Id> relatedServiceSessionIds = vertic_Utils.sObjects.getIdFieldValues(expenses, Expense__c.Service_Session__c);
        Set<Id> relatedProgramIds = new Set<Id>();

        Map<Id, pmdm__ServiceSession__c> serviceSessions = new Map<Id, pmdm__ServiceSession__c>([
            SELECT Id,Name, Program__c
            FROM pmdm__ServiceSession__c
            WHERE Id IN :relatedServiceSessionIds
        ]);

        List<Funding_Allocation__c> fundingAllocations = [
            SELECT Id, Service_Session__c, Funds_Remaining__c, CreatedDate
            FROM Funding_Allocation__c
            WHERE Status__c = 'Active' AND Service_Session__c IN :serviceSessions.keySet()
            ORDER BY CreatedDate DESC
        ];

        relatedProgramIds = vertic_Utils.sObjects.getIdFieldValues(serviceSessions.values(), pmdm__ServiceSession__c.Program__c);

        List<Program_Budget_Allocation__c> programBudgetAllocations = [
            SELECT Id, Program__c, Funds_Remaining__c
            FROM Program_Budget_Allocation__c
            WHERE  Status__c = 'Active' AND Program__c IN :relatedProgramIds
            ORDER BY CreatedDate DESC
        ];

        List<Funding_Allocation__c> parentFundingAllocations = new List<Funding_Allocation__c>();
        List<Program_Budget_Allocation__c> parentProgramBudgetAllocations = new List<Program_Budget_Allocation__c>();

        for(Expense__c expenseRecord: expenses){
            Boolean expenseToBeProcessed = (expenseRecord.Status__c.equals('Planning') ||  expenseRecord.Status__c.equals('Paid'))
                && expenseRecord.Program_Budget_Allocation__c == null && expenseRecord.Funding_Allocation__c == null;

            if(expenseToBeProcessed && expenseRecord.Service_Session__c != null){
                for(Funding_Allocation__c fundingAllocation: fundingAllocations){
                    if(fundingAllocation.Service_Session__c.equals(expenseRecord.Service_Session__c)
                        && (fundingAllocation.Funds_Remaining__c > expenseRecord.Expense_Amount__c || expenseRecord.Expense_Amount__c == null)){
                        parentFundingAllocations.add(fundingAllocation);
                    }
                }
            }

            if(parentFundingAllocations.isEmpty() != true){
                Funding_Allocation__c fundingAllocation = (Funding_Allocation__c)vertic_Utils.arrays.firstOrNull(parentFundingAllocations);
                expenseRecord.Funding_Allocation__c = fundingAllocation?.Id;
                continue;
            }
            if(expenseToBeProcessed && expenseRecord.Service_Session__c != null) {
                for (Program_Budget_Allocation__c programBudgetAllocation : programBudgetAllocations) {
                    if (programBudgetAllocation.Program__c != null && serviceSessions.get(expenseRecord.Service_Session__c).Program__c != null
                        && programBudgetAllocation.Program__c.equals(serviceSessions.get(expenseRecord.Service_Session__c).Program__c)
                        && (programBudgetAllocation.Funds_Remaining__c > expenseRecord.Expense_Amount__c || expenseRecord.Expense_Amount__c == null)) {
                        parentProgramBudgetAllocations.add(programBudgetAllocation);
                    }
                }
            }

            if(parentProgramBudgetAllocations.isEmpty() != true){
                Program_Budget_Allocation__c programBudgetAllocation = (Program_Budget_Allocation__c)vertic_Utils.arrays.firstOrNull(parentProgramBudgetAllocations);
                expenseRecord.Program_Budget_Allocation__c = programBudgetAllocation?.Id;
                continue;
            }

            expenseRecord.addError('There are no funds available for this expense, please review the Funding Allocations assigned to the Service Session and the Program Budget Allocation assigned to the Program to ensure funds are available.');
        }
    }
}