objects/LGA__c.object
<CustomObject>
    <label>LGA</label>
    <nameField>
        <label>LGA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LGAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Postcode</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateContactsBatch.cls
global without sharing class UpdateContactsBatch implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        fflib_QueryFactory queryFactory = new fflib_QueryFactory(Contact.SObjectType);
        Set<String> fields = Contact.SObjectType.getDescribe().fields.getMap().keySet().clone();
        queryFactory.selectFields(fields);
        queryFactory.setCondition('MailingCity != \'\' AND MailingPostalCode != \'\' AND LGA__c = \'\'');
        return Database.getQueryLocator(queryFactory.toSOQL());
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        updateContacts(scope);
    }

    global void finish(Database.BatchableContext BC) {}

    global static void updateContacts(List<Contact> contacts) {

        Set<String> cityValues = vertic_Utils.sObjects.getStringFieldValues(contacts, 'MailingCity');
        Set<String> postcodeValues = vertic_Utils.sObjects.getStringFieldValues(contacts, 'MailingPostalCode');

        List<Postcode__c> postcodes = [
            SELECT Suburb__c, Postcode__c, LGA__c
            FROM Postcode__c
            WHERE Suburb__c IN :cityValues AND Postcode__c IN :postcodeValues AND LGA__c != '' AND Suburb__c != '' AND Postcode__c != ''
        ];

        for(Contact contact: contacts){
            for(Postcode__c postcode: postcodes){
                if(contact.MailingCity == postcode.Suburb__c && contact.MailingPostalCode == postcode.Postcode__c){
                    contact.LGA__c = postcode.LGA__c;
                    continue;
                }
            }
        }
        update contacts;
    }
}